name: Publish Adblock Rule Collection to Release

on:
  schedule:
    - cron: "*/20 * * * *"  # 每20分钟运行一次
  push:
    branches:
      - main  # 在main分支上运行
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  publish_release:
    runs-on: ubuntu-latest  # 使用最新的Ubuntu环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 签出仓库的代码

    - name: Set up GitHub CLI
      uses: actions/setup-gh@v2  # 设置GitHub CLI环境
      with:
        token: ${{ secrets.TOKEN }}  # 使用GitHub secret中的TOKEN

    - name: Create Release
      id: create_release
      run: |
        # 获取当前日期和时间作为release的tag和名称
        RELEASE_TAG=$(date +%Y%m%d%H%M)
        RELEASE_NAME="Adblock Rule Collection - $RELEASE_TAG"

        # 创建release
        gh release create $RELEASE_TAG \
          --title "$RELEASE_NAME" \
          --notes "Automated release of Adblock Rule Collection" \
          --target main \
          --draft
      env:
        TOKEN: ${{ secrets.TOKEN }}  # 使用GitHub secret中的TOKEN

    - name: Upload Asset
      run: |
        # 获取创建的release的ID
        RELEASE_TAG=$(date +%Y%m%d%H%M)

        # 上传ADBLOCK_RULE_COLLECTION.txt文件到release
        gh release upload $RELEASE_TAG ADBLOCK_RULE_COLLECTION.txt
      env:
        TOKEN: ${{ secrets.TOKEN }}  # 使用GitHub secret中的TOKEN
